export const IPC = {
  PTY_CREATE: 'pty:create',
  PTY_DATA: 'pty:data',
  PTY_WRITE: 'pty:write',
  PTY_RESIZE: 'pty:resize',
  PTY_KILL: 'pty:kill',
  PTY_EXIT: 'pty:exit',
  CONFIG_GET: 'config:get',
  CONFIG_SET: 'config:set',
  SESSION_SAVE: 'session:save',
  SESSION_LOAD: 'session:load',
  CONFIG_OPEN: 'config:open',
  OPEN_PATH: 'shell:openPath',
  DETACH_CREATE: 'detach:create',
  DETACH_CLOSE: 'detach:close',
  DETACH_CLOSED: 'detach:closed',
  DETACH_FOCUS: 'detach:focus',
  COPILOT_LIST_SESSIONS: 'copilot:listSessions',
  COPILOT_GET_SESSION: 'copilot:getSession',
  COPILOT_SEARCH_SESSIONS: 'copilot:searchSessions',
  COPILOT_SESSION_UPDATED: 'copilot:sessionUpdated',
  COPILOT_SESSION_ADDED: 'copilot:sessionAdded',
  COPILOT_SESSION_REMOVED: 'copilot:sessionRemoved',
  COPILOT_START_WATCHING: 'copilot:startWatching',
  COPILOT_STOP_WATCHING: 'copilot:stopWatching',
  COPILOT_GET_PROMPTS: 'copilot:getPrompts',
  CLAUDE_CODE_LIST_SESSIONS: 'claude-code:listSessions',
  CLAUDE_CODE_GET_SESSION: 'claude-code:getSession',
  CLAUDE_CODE_SEARCH_SESSIONS: 'claude-code:searchSessions',
  CLAUDE_CODE_SESSION_UPDATED: 'claude-code:sessionUpdated',
  CLAUDE_CODE_SESSION_ADDED: 'claude-code:sessionAdded',
  CLAUDE_CODE_SESSION_REMOVED: 'claude-code:sessionRemoved',
  CLAUDE_CODE_START_WATCHING: 'claude-code:startWatching',
  CLAUDE_CODE_STOP_WATCHING: 'claude-code:stopWatching',
  CLAUDE_CODE_GET_PROMPTS: 'claude-code:getPrompts',
  VERSION_UPDATE_STATUS: 'version:updateStatus',
  VERSION_GET_UPDATE: 'version:getUpdate',
  VERSION_CHECK_NOW: 'version:checkNow',
  VERSION_GET_APP_VERSION: 'version:getAppVersion',
  VERSION_RESTART_AND_UPDATE: 'version:restartAndUpdate',
  CLIPBOARD_SAVE_IMAGE: 'clipboard:saveImage',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
